site_name: JiangnanWiki
site_description: 江南大学学习与生活知识库
site_author: d4yt1m3
site_url: https://d4yt1m3.github.io/JiangnanWiki/
repo_url: https://github.com/d4yt1m3/JiangnanWiki
repo_name: d4yt1m3/JiangnanWiki

theme:
  name: material
  language: zh
  logo: assets/images/jiangnan-university-logo-white.png
  favicon: assets/images/jiangnan-university-logo-white.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-night
        name: 切换至深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: 切换至浅色模式
  features:
    - navigation.top
    - search.suggest
    - search.highlight

nav:
  - 欢迎: index.md
  - 科创俱乐部:
      - 人工智能与计算机学院:
          - ACM 俱乐部: 科创俱乐部/人工智能与计算机学院/ACM俱乐部.md
          - 信息安全俱乐部: 科创俱乐部/人工智能与计算机学院/信息安全俱乐部.md
          - 智能系统俱乐部: 科创俱乐部/人工智能与计算机学院/智能系统俱乐部.md
          - 数字媒体俱乐部: 科创俱乐部/人工智能与计算机学院/数字媒体俱乐部.md
          - 计算机系统俱乐部: 科创俱乐部/人工智能与计算机学院/计算机系统俱乐部.md
          - 昇腾鲲鹏 AI 创新俱乐部: 科创俱乐部/人工智能与计算机学院/昇腾鲲鹏AI创新俱乐部.md
      - 自动化与智能科学学院:
          - 数据赋能俱乐部: 科创俱乐部/自动化与智能科学学院/数据赋能俱乐部.md

plugins:
  - search:
      lang:
        - zh
        - en
